version: '3'
services:
    forum-postgres:
        container_name: forum-postgres
        image: postgres:17.0-alpine3.20
        restart: unless-stopped
        user: "${UID}:${GID}"
        environment:
            - TZ=Asia/Seoul
            - LANG=ko_KR.UTF-8
            - LANGUAGE=ko_KR:ko:en_US:en
            - LC_COLLATE=ko_KR.UTF-8
            - LC_TYPE=ko_KR.UTF-8
            - LC_ALL=ko_KR.UTF-8
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./data:/var/lib/postgresql/data/pgdata
            - ./entrypoint:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432